# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: First Github Action Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install
      
    - name: Build
      run: npm run build --if-present
      
    - name: Launch test
      run: npm test
